"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schema for my building block'
type: object
properties:
  title:
    type: string
    format: string
  identifier:
    type: string
required:
  - title
  - identifier
